CREATE TABLE operadoras_cadastral (
    REGISTRO_ANS VARCHAR(20) PRIMARY KEY,
    CNPJ VARCHAR(20) NOT NULL,
    RAZAO_SOCIAL VARCHAR(255),
    NOME_FANTASIA VARCHAR(255),
    UF CHAR(2),
    CIDADE VARCHAR(100),
    INDEX idx_cnpj(CNPJ),
    INDEX idx_uf (UF)
);

CREATE TABLE detalhe_despesas (
    ID INT AUTO_INCREMENT PRIMARY KEY
    REG_ANS VARCHAR(20).
    DATA_EVENTO DATE,
    EVENTO VARCHAR(255),
    DESCRICAO VARCHAR(255),
    VALOR_COMERCIAL DECIMAL(15,2),
    ANO_MES VARCHAR(7)
    FOREIGN KEY (REG_ANS) REFERENCES operadoras_cadastral(REGISTRO_ANS)
);

CREATE TABLE despesas_agregadas (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(255)
    UF CHAR(2),
    TOTAL_DESPESAS DECIMAL(15,2)
    MEDIA_TRIMESTRAL DECIMAL(15,2)
    DESVIO_PADRAO DECIMAL(15,2),
    DATA_PROCESSAMENTO DATE
)

